### ISSUE TITLE
Name from script definition should not overwrite expected name

### ISSUE THREAD

**Issue by dennisdupont** [sethreno/schemazen#105]
I'm not sure if this is an SMO bug or SchemaZen issue - it seems if you rename a database object, the old name hangs around and that is what gets scripted out instead of the current name.  This causes a warning message like "Name from script definition 'Wilma' does not match expected name 'Fred'" but the user still must go repair each object manually.

**Comment by sethreno** [comment]
This is a bug in whatever was used to rename the object (SSMS?). The object has a name that is stored in the sys tables. It also has a name that is included in the script text. These names don't have to match. SchemaZen is dumping the database exactly "as is". The warning is a feature of SchemaZen and was added because typically people want these names to match.

**Comment by manu-silicon** [comment]
@sethreno I agree with you that having the warning is good but not everyone is an expert and I have no idea how to update the sys tables properly.

To avoid the warnings, I've used the naive way to delete my object and then adding a new one with the new name. I'm sure there is better way to do this. It would help if we could get a hint at where the mismatch occurs.

**Comment by sethreno** [comment]
@manu-silicon Dropping and recreating is the only way I know to fix this issue. I'll update the warning to try and be more helpful. Here's the new message:

`$"Name from script definition '{name}' does not match expected value from sys.objects.name '{Name}'. This can be corrected by dropping and recreating the object.";`
